### ISSUE TITLE
Unable to find a decode

### ISSUE THREAD

**Issue by denchic45** [alialbaali/Kamel#26]
Error when trying to load svg image.

Sample:
```
    KamelImage(lazyPainterResource(
            Url("https://www.svgrepo.com/show/424692/energy-factory-illustration-7.svg")),
            contentDescription = null,
            onFailure = { it.printStackTrace() }
        )
```

StackTrace:
```
java.lang.IllegalStateException: Unable to find a decoder for io.kamel.core.decoder.Decoder<androidx.compose.ui.graphics.painter.Painter>
	at io.kamel.core.ImageLoadingKt.requestSvgResource(ImageLoading.kt:168)
	at io.kamel.core.ImageLoadingKt.access$requestSvgResource(ImageLoading.kt:1)
	at io.kamel.core.ImageLoadingKt$loadSvgResource$1.invokeSuspend(ImageLoading.kt:74)
	at io.kamel.core.ImageLoadingKt$loadSvgResource$1.invoke(ImageLoading.kt)
	at io.kamel.core.ImageLoadingKt$loadSvgResource$1.invoke(ImageLoading.kt)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt.catchImpl(Errors.kt:156)
	at kotlinx.coroutines.flow.FlowKt.catchImpl(Unknown Source)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(SafeCollector.common.kt:113)
	at androidx.compose.runtime.SnapshotStateKt__SnapshotFlowKt$collectAsState$1$2.invokeSuspend(SnapshotFlow.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

**Comment by alialbaali** [comment]
Desktop or Android?

**Comment by denchic45** [comment]
Desktop

**Comment by alialbaali** [comment]
Are you using custom KamelConfig? If so, make sure to use include `svgDecoder()`.

**Comment by denchic45** [comment]
No, I don't seem to use

**Comment by alialbaali** [comment]
Well, you need to include it manually as this is a platform based implementation. 

Here's how you do it:

```
KamelConfig {
    takeFrom(KamelConfig.Default)
    svgDecoder()
}
```

**Comment by alialbaali** [comment]
I have updated the sample, for better understanding.

**Comment by denchic45** [comment]
Thank you! I will try today or tomorrow
